name: XMines
author: LuciferVerma
website: www.cosmocraft.ml
main: LuciferVerma\XMines\Main
version: 1.0.0
api: [3.0.0]
discription: with this plugin you can make mines. where people will be able to mine other ore and but they can't mine other things like stone, wood etc. basically they can only mine ores. 
how_to_use: go to config.yml and put the world name where you want to make mine. i have sime added ore ids in the list but if you want player to mine other items then add the id of that item and are good to go. restart the server.
note: this plugin don't respawn ores. you will need a ore regenerating plugin to let ore's respawn. good luck. im working on that plugin too. 
